### ISSUE TITLE
sallybot.exe in debug profile does not exist

### ISSUE THREAD

**Issue by gmarc-goop** [DeSinc/SallyBot#11]
Not sure whats wrong here, as it turns out google was not my best friend here. But I suspect I am on a newer version of visual studio. Appreciate any help and tips. 

![image](https://user-images.githubusercontent.com/130025231/230270602-dba75476-5a84-48e2-b1d0-7614e30c74f1.png)

**Comment by DeSinc** [comment]
Redownload the program.cs and place in your Server's ID, and your bot's ID into the relevant sections in caps lock that cause errors in the IDE.
