### ISSUE TITLE
Latest commit of Program.cs does not build due to errors

### ISSUE THREAD

**Issue by AceGamerR6** [DeSinc/SallyBot#17]
![image](https://user-images.githubusercontent.com/94653587/230969520-e36074e5-cf8c-4ad8-8d85-6f60219339ba.png)

**Comment by IrfanIkhwan** [comment]
![Untitled](https://user-images.githubusercontent.com/85914295/231021324-f787a9e6-fed5-43b3-a1c5-1aa619dda7e5.png)
same issue

**Comment by DeSinc** [comment]
lol clone the repo again my mistake
