### ISSUE TITLE
sallybotMatch "System.NullReferenceException: 'Object reference not set to an instance of an object.'" when message contains bot name.

### ISSUE THREAD

**Issue by Jakoski360** [DeSinc/SallyBot#19]
![image](https://user-images.githubusercontent.com/5264946/231291643-89dd8e3c-a844-4aaa-9af0-bd926a7c5fd5.png)

Cloned repo and merged bot and guild variables from previously working commit 2 days ago.

sallybotMatch is null throwing System.NullReferenceException, continuing after break sends "Object reference not set to an instance of an object." to console output

**Comment by ErnestoTheGamer** [comment]
yea i encountered the same issue, the regex statement are not the best and at least for me do not work properly, which causes null to be returned.

I've made my own fix by writing some poorly written regex statements, hopefully it works for you too.

`                // detect when a user types the bot name and a questionmark, or the bot name followed by a comma.
                // Examples: 
                // ok ->sally,<- it's go time. tell me a story
                // how many miles is a kilometre ->sallybot?<-
                // hey ->sallybot,<- are you there?
                bool sallybotMatch = Regex.IsMatch(inputMsg, @$"(?:.*{botName}.*\?.*|{botName}\s*,)", RegexOptions.IgnoreCase);

                bool startsWithSallybot = Regex.IsMatch(inputMsg, @$"(?:^{botName})", RegexOptions.IgnoreCase);

                bool shortSallybotMatch = Regex.IsMatch(inputMsg, @$"(?:.*{botName}.*)", RegexOptions.IgnoreCase) && Msg.Content.Length < 25;

                if (Msg.MentionedUsers.Contains(MainGlobal.Server.GetUser(botUserId))
                    || sallybotMatch // sallybot, or sallybot? query detected
                    || startsWithSallybot
                    || (lastLineWasSallyBot && Msg.Content.EndsWith("?")) // if last msg was sallybot and user followed up with question
                    || shortSallybotMatch) // or very short sentences mentioning sally`

**Comment by DeSinc** [comment]
Update the repo. I left old code in by mistake.

It was trying to grab nickname and when there was no nickname present it was failing.

Now it grabs nickname if present in the MainLoop.cs file. Make sure you update BOTH program.cs and mainloop.cs

**Comment by Shizzkizz** [comment]
Issue still seems to be happening even with the updated code. Will have to try again as it could be my end.

**Comment by DeSinc** [comment]
make sure you get all files, I updated every file almost except functions.cs pretty much.

I also updated it again like hours ago so download all files again if you haven't.

if you still get that object reference not set to instance of object error, send it here.

**Comment by Jakoski360** [comment]
I'm not getting the issue anymore with the latest files.

**Comment by DeSinc** [comment]
thought so - fixed a lot of those stray bugs today. glad to hear it
