### ISSUE TITLE
Issue with stable diffusion not being able to load loras 

### ISSUE THREAD

**Issue by NarksClueless** [DeSinc/SallyBot#22]
When having the prompts for the stable diffusion be entirely user input and not the LLM, if you try to use a lora it will come back with "couldn't find Lora with name XXXXX". like this.

![image](https://user-images.githubusercontent.com/130717494/231915413-a614cf87-2758-4eb4-85e0-51688236c548.png)

Sure it's not a massive issue but being able it change the outputs with a lora would be nice!

**Comment by DeSinc** [comment]
either select a lora in the webui by enabling the dropdown for it in the SD webui settings, or try to provide <lora:Lora_Name:1> in the prompt itself which might work too.

**Comment by DeSinc** [comment]
First test: Confirming: selecting a lora from the webui does cause all of the bot's prompts to become shaped by that lora.

**Comment by DeSinc** [comment]
Second test: replacing llm's prompt with direct user prompt: I can't get it to recognise the <lora:Lora_Name> tag. I think this must be a webui only feature to put it in with the prompt text.

There might be some param you can pass to the webui for this but I'm not sure what it is

**Comment by DeSinc** [comment]
warning: if you select a lora in the drop down it seems atm in my version of SD there is no way to UNselect this lora, quite annoying. I think I have to move the lora out of the folder to get it to stop selecting it in the webui. not even a reload clears it.

**Comment by DeSinc** [comment]
well, there is no lora tags in stable diffusion API. I had a look at the code to see if I could add it myself but no luck, I just don't understand what it needs to add that field and select a lora based on it.

Until SD adds a lora field for the input json in the API, the only way to select a lora appears to be going into the webui and selecting it in the settings.

**Comment by DeSinc** [comment]
> When having the prompts for the stable diffusion be entirely user input and not the LLM, if you try to use a lora it will come back with "couldn't find Lora with name XXXXX". like this.
> 
> ![image](https://user-images.githubusercontent.com/130717494/231915413-a614cf87-2758-4eb4-85e0-51688236c548.png)
> 
> Sure it's not a massive issue but being able it change the outputs with a lora would be nice!

p.s: what did you do to get this lora error back btw?

**Comment by NarksClueless** [comment]
Sorry so when i changed it to allower user input for the prompts by doing this 
![image](https://user-images.githubusercontent.com/130717494/231946141-2691f528-eb00-497d-b2d4-ebb9c7b6b911.png)

If you try and use a lora like this "  <<lora:NecoArc1:1>> " it should show that error. 

I should have mentioned that selecting a lora via the dropdown is trash because you can't unselect it and it permanently mixes it with everything else.

**Comment by DeSinc** [comment]
yeah I have no clue what he did or what he's talking about. I read it 3 times but I don't have enough information or context to be able to connect any dots. frankly I have no clue how they all know what he meant in that thread. lmao

**Comment by NarksClueless** [comment]
Understandable, appreciate the effort on the project as a whole. 

If i figure it out i'll post it..

**Comment by NarksClueless** [comment]
Figured it out, somewhere some how you're filtering out capitals or something

If you rename the lora using all lower case it can prompt without issue. This might not be useful to you but it's good to know just in case you feel like letting people generate art of characters, memes, etc.

**Comment by DeSinc** [comment]
> Figured it out, somewhere some how you're filtering out capitals or something, idk much about coding or how to edit code that well.
> 
> If you rename the lora using all lower case it can prompt without issue. This might not be useful to you but it's good to know just in case you feel like letting people generate art of characters, memes, etc.

definitely not filtering out capitals out of the message, and definitely the lora name is not caps sensitive in the webui either. It must be a SD API thing that's doing it. good find.
