### ISSUE TITLE
"Failed to generate the bucket id for this operation"

### ISSUE THREAD

**Issue by fennadez** [DeSinc/SallyBot#24]
No any problems while runing debug but Sallybot didnt respond anything just online in server

**Comment by DeSinc** [comment]
what error in sally console? Oobabooga needs to run with --extensions api and --notebook, and you must also remove ``--cai-chat`` and ``--chat`` flags from the launch .bat file. default API of 7860 does not work correctly, only --extensions api works correctly. 

if using Dalai, you need to run npx dalai serve in cmd to run the server, and see "Connected to Dalai server" in sally console.

**Comment by DeSinc** [comment]
closing because no reply, code definitely works so it's an issue with how they had it configured which may be solved by now
