### ISSUE TITLE
JSON Errors when using Oobabooga Text Generation

### ISSUE THREAD

**Issue by VSS-Vintorez** [DeSinc/SallyBot#27]
My only modification was commenting the only display the first line of error for a detailed report.
Error: 
![image](https://user-images.githubusercontent.com/24535879/233806384-1c1e18f0-3bca-40a2-8a2f-5a5ec0c324e8.png)
OS: Windows 10 22H2
Oobabooga installed with the 1-click installer, with xformers.
It works just fine on Dalai, but I want to use my GPU for both Text Generation and Stable Diffusion

**Comment by DeSinc** [comment]
hmm. I just updated by oobabooga and ran sallybot and it seems to work ok for me on this end. My only suggestion would be to try update ooba on your end first, then after updating if it still doesn't work, verify the webui works to generate text.

Also, make sure you are using the right args on your oobabooga, which now needs to be written in the webui.py file in the main ooba folder with all the .bat files now. Check readme (github main page for sallybot) at the ooba instructions section and you'll see we updated them to reflect the new process now, and all the args that you need to paste in are there

**Comment by DeSinc** [comment]
P.S: you have to use --extensions api on oobabooga for now as default API was giving me bugs and does not work right.

I get the feeling ooba cycled around to using the default API here and is getting the json bug I mentioned. Try restarting sallybot and as long as --extensions api is running on ooba, it should connect.

**Comment by VSS-Vintorez** [comment]
I was using --extensions api but I found the issue, other apps taking up the ports and needing to update it, Thanks!
