### ISSUE TITLE
SallyBot keeps messing up the time

### ISSUE THREAD

**Issue by Angel-Sb** [DeSinc/SallyBot#30]
I have tried to add a new time zone to the code.
-
![image](https://github.com/DeSinc/SallyBot/assets/134013141/2aecbfbc-4766-4569-9531-584d4a9cc979)
I have checked that the time zone id is correct to windows 11 and that the references are right.
-
![image](https://github.com/DeSinc/SallyBot/assets/134013141/148a7fd1-9709-4fb4-b77c-648caf97cecb)
![image](https://github.com/DeSinc/SallyBot/assets/134013141/1b9014dc-1a90-4f87-9602-41cc36abb7ff)

Every time i ask sally for the time she couldn't be any more random.
 -
![image](https://github.com/DeSinc/SallyBot/assets/134013141/85304e57-e8d4-4ec4-8196-ce163704b887)

![image](https://github.com/DeSinc/SallyBot/assets/134013141/6c2ff731-0bb2-4d9f-b2fc-42e9dcb8bdf8)

![image](https://github.com/DeSinc/SallyBot/assets/134013141/c7d77922-3831-44cd-b8a3-62bf8ef1659e)
![image](https://github.com/DeSinc/SallyBot/assets/134013141/413ce81b-1607-4c04-9f42-0437d7f64758)

### Any help really appreciated!

**Comment by agr19** [comment]
the time configuration in the code is to be referenced in the image generation prompt. it has no relation with the language model itself. the language model has no perception of time.

**Comment by Angel-Sb** [comment]
Thanks for commenting. I have noticed that the code for time configuration is on image generation prompt file (function.cs) and that the language model doesn't have perception of time. My problem is that even tho everything seems normal code wise the actual result is a bit weird.

**Comment by DeSinc** [comment]
I was able to get a fairly stable result of the LLM working out what time it was only by using a better model. The current time in japan is written into the character prompt as you'll see by default in the github code but a lot of the LLMs out there just simply do not listen to it and speak a random time. If you can get your hands on a good 13B model, it seems to solve the issue, but it may also be possible with a high quality 7B model.

I would recommend checking out a few models and seeing what results you get. Check online what the best model is nowadays, I've heard great things about wizardLM and guanaco.

**Comment by Angel-Sb** [comment]
Thank you a lot! I will download and try different models to see what works best as you said.
