### ISSUE TITLE
enable_hr broken output

### ISSUE THREAD

**Issue by BPplays** [DeSinc/SallyBot#34]
when enable_hr is true i get ![](https://cdn.discordapp.com/attachments/1127550960340840498/1127650168276267008/cutepic.png)

here is my var payload

```cs
            var payload = new JObject
            {
                { "prompt", imgPrompt },
                { "negative_prompt", imgNegPrompt},
                { "steps", 45 },
                { "width", width },
                { "height", height },
                { "send_images", true },
                { "sampler_name", "Euler" }, // DDIM set this to "DPM++ 2M SDE Karras" if you want slightly higher quality images, but slower image generation
                { "override_settings", overrideSettings },
                { "enable_hr", true },
                { "hr_second_pass_steps", 40 },
                { "hr_scale", 1.7 }
            };
```

**Comment by DeSinc** [comment]
you need a few more options, here use mine, this works fine on my end:

​```
            var payload = new JObject
            {
                { "prompt", imgPrompt },
                { "negative_prompt", imgNegPrompt},
                { "steps", 24 },
                { "width", width },
                { "height", height },
                { "send_images", true },
                { "sampler_name", "DPM++ SDE Karras" },
                { "enable_hr", true },
                { "denoising_strength", 0.3 },
                { "hr_scale", 2 },
                { "hr_resize_x", width*2 },
                { "hr_resize_y", height*2 },
                { "hr_upscaler", "R-ESRGAN 4x+ Anime6B" },
                { "hr_second_pass_steps", 5 },
                { "override_settings", overrideSettings }
            };
```
